### ISSUE TITLE
Can't get it work with -file

### ISSUE THREAD

**Issue by YouriT** [maxcnunes/waitforit#9]
I can't get it working with a JSON config file.
Here is the content:
```json
{
  "configs": [{
    "fullConnection": "http://google.com",
    "timeout": 40
  }]
}
```

And I'm getting this error:
```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x402636]

goroutine 5 [running]:
panic(0x62f900, 0xc42000e040)
	/usr/local/opt/go/libexec/src/runtime/panic.go:500 +0x1a1
main.pingTCP(0x0, 0x28, 0xc42000f180, 0x61cba0)
	/Users/maxcnunes/Development/go/src/github.com/maxcnunes/waitforit/network.go:61 +0xa6
main.dial(0x0, 0x28, 0x0, 0x0)
	/Users/maxcnunes/Development/go/src/github.com/maxcnunes/waitforit/network.go:14 +0xe1
main.parallelDial(0x0, 0x28, 0xc4200501e0)
	/Users/maxcnunes/Development/go/src/github.com/maxcnunes/waitforit/network.go:29 +0x35
created by main.handleFileConfig
	/Users/maxcnunes/Development/go/src/github.com/maxcnunes/waitforit/file.go:25 +0x129
```

Using v1.4.0
Works fine with `-full-connection`

**Comment by YouriT** [comment]
Okay, that feature isn't built in 1.4.0 that's why!

**Comment by YouriT** [comment]
Could you eventually think about releasing? I like the concept of raw tcp for much services that don't expose an http service

**Comment by YouriT** [comment]
It was built in under `connectionString` in fact. Well anyhow not a big deal. But it seems that `timeout` property isn't get because it says: `Waiting 10 seconds` event though I set it to 40.

**Comment by YouriT** [comment]
well my bad.. everything works fine :) great job!
